Repository honeycombio/honeycomb-lambda-extension, pull requests merged in 2021-11, with the labels that each got.

#64 Prepare v10.0.2 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump patch

#65 put GOARCH into user agent
  main.go
Labels: type: enhancement, type: maintenance, version: bump patch

#70 docs: update layer version
  README.md
  RELEASING.md
Labels: type: documentation, version: no bump, merge at will
