Repository honeycombio/honeycomb-lambda-extension, pull requests merged in 2022-10, with the labels that each got.

#98 feat: configurable event batch send timeout
  .circleci/config.yml
  README.md
  go.mod
  go.sum
  main.go
  main_test.go
Labels: type: enhancement, version: bump minor

#102 (no changelog): only warn about invalid TIMEOUT env var if it is set
  main.go
Labels: type: bug, version: no bump

#104 [release] v10.4.0 - Layer version 11
  CHANGELOG.md
  README.md
  version.go
Labels: version: no bump, type: maintenance

#103 maint: release process updates for friendlier ARNs
  .circleci/config.yml
  .gitignore
  Makefile
  main.go
  publish.sh
  version.go
Labels: type: maintenance, version: bump major

#107 maint: add config for gh release notes organization
  .github/release.yml
Labels: version: no bump, type: maintenance

#108 [release] Prepare v11.0.0
  .circleci/config.yml
  CHANGELOG.md
  README.md
  RELEASING.md
Labels: type: maintenance, no-changelog

#110 maint: remove interstitial linux subdir from S3 publish
  .circleci/config.yml
Labels: type: maintenance, no-changelog

#111 feat: configurable HTTP transport connect timeout
  README.md
  eventpublisher/eventpublisher.go
  eventpublisher/eventpublisher_test.go
  logsapi/server.go
  main.go
  main_test.go
Labels: type: enhancement, status: oncall

#112 maint: refactor config and simplify main()
  eventprocessor/eventprocessor.go
  eventpublisher/eventpublisher.go
  eventpublisher/eventpublisher_test.go
  extension/config.go
  extension/config_test.go
  logsapi/client.go
  logsapi/client_test.go
  logsapi/server.go
  main.go
  main_test.go
Labels: version: no bump, type: maintenance

#113 release: Prepare v11.1.0
  CHANGELOG.md
Labels: type: maintenance, no-changelog

#114 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: version: no bump, type: maintenance, merge at will

#117 remove duplicate GOARCH in user-agent
  eventpublisher/eventpublisher.go
  eventpublisher/eventpublisher_test.go
Labels: version: no bump, type: maintenance
